import Head from 'next/head'
import { Inter } from 'next/font/google'


import { _Main } from '@/_views/ScheduleComponents/Main'
import { Layout } from '@/_views/ui/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Расписание</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <_Main />
      </Layout>


    </>
  )
}
